export default {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'style',
        'refactor',
        'perf',
        'test',
        'build',
        'ci',
        'chore',
        'revert',
      ],
    ],
    'scope-enum': [
      2,
      'always',
      [
        'init',
        'auth',
        'layout',
        'theme',
        'i18n',
        'rbac',
        'user',
        'video',
        'comment',
        'dynamic',
        'banner',
        'notification',
        'site',
        'deps',
        'config',
        'release',
      ],
    ],
    'scope-empty': [1, 'never'],
    'subject-case': [0],
    'header-max-length': [2, 'always', 100],
  },
}
