import { computed } from 'vue'
import { darkTheme, type GlobalThemeOverrides } from 'naive-ui'
import { useTheme, type ThemeName } from './useTheme'

/**
 * 获取 CSS Variable 的实际值
 */
function getCssVar(name: string): string {
  return getComputedStyle(document.documentElement).getPropertyValue(name).trim()
}

/**
 * 各主题的 Naive UI GlobalThemeOverrides 配置
 * 与 Design Tokens 对齐
 */
const themeOverridesMap: Record<ThemeName, GlobalThemeOverrides> = {
  pearl: {
    common: {
      primaryColor: '#5c7cfa',
      primaryColorHover: '#4c6ef5',
      primaryColorPressed: '#4263eb',
      primaryColorSuppl: '#5c7cfa',
      infoColor: '#4dabf7',
      infoColorHover: '#339af0',
      infoColorPressed: '#1c7ed6',
      infoColorSuppl: '#4dabf7',
      successColor: '#51cf66',
      successColorHover: '#40c057',
      successColorPressed: '#37b24d',
      successColorSuppl: '#51cf66',
      warningColor: '#ffd43b',
      warningColorHover: '#fcc419',
      warningColorPressed: '#fab005',
      warningColorSuppl: '#ffd43b',
      errorColor: '#ff6b6b',
      errorColorHover: '#fa5252',
      errorColorPressed: '#f03e3e',
      errorColorSuppl: '#ff6b6b',
      textColorBase: '#212529',
      textColor1: '#212529',
      textColor2: '#495057',
      textColor3: '#868e96',
      textColorDisabled: '#ced4da',
      placeholderColor: '#868e96',
      placeholderColorDisabled: '#ced4da',
      iconColor: '#495057',
      iconColorHover: '#212529',
      iconColorPressed: '#212529',
      iconColorDisabled: '#ced4da',
      dividerColor: '#dee2e6',
      borderColor: '#dee2e6',
      closeIconColor: '#868e96',
      closeIconColorHover: '#495057',
      closeIconColorPressed: '#212529',
      closeColorHover: 'rgba(0, 0, 0, 0.06)',
      closeColorPressed: 'rgba(0, 0, 0, 0.1)',
      clearColor: '#868e96',
      clearColorHover: '#495057',
      clearColorPressed: '#212529',
      scrollbarColor: 'rgba(0, 0, 0, 0.25)',
      scrollbarColorHover: 'rgba(0, 0, 0, 0.35)',
      progressRailColor: '#dee2e6',
      railColor: '#dee2e6',
      popoverColor: '#ffffff',
      tableColor: '#ffffff',
      cardColor: '#ffffff',
      modalColor: '#ffffff',
      bodyColor: '#f8f9fa',
      tagColor: '#f1f3f5',
      avatarColor: '#dee2e6',
      invertedColor: '#212529',
      inputColor: '#ffffff',
      codeColor: '#f1f3f5',
      tabColor: '#ffffff',
      actionColor: '#f1f3f5',
      tableHeaderColor: '#f8f9fa',
      hoverColor: 'rgba(0, 0, 0, 0.04)',
      tableColorHover: 'rgba(0, 0, 0, 0.04)',
      tableColorStriped: 'rgba(0, 0, 0, 0.02)',
      pressedColor: 'rgba(0, 0, 0, 0.08)',
      opacityDisabled: '0.5',
      inputColorDisabled: '#f1f3f5',
      buttonColor2: 'rgba(92, 124, 250, 0.1)',
      buttonColor2Hover: 'rgba(92, 124, 250, 0.15)',
      buttonColor2Pressed: 'rgba(92, 124, 250, 0.2)',
      boxShadow1: '0 1px 3px 0 rgba(0, 0, 0, 0.08), 0 1px 2px -1px rgba(0, 0, 0, 0.08)',
      boxShadow2: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -2px rgba(0, 0, 0, 0.1)',
      boxShadow3: '0 10px 15px -3px rgba(0, 0, 0, 0.12), 0 4px 6px -4px rgba(0, 0, 0, 0.12)',
      borderRadius: '8px',
      borderRadiusSmall: '6px',
      fontFamily:
        'Inter, SF Pro Display, -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Helvetica Neue, Arial, Noto Sans, PingFang SC, Hiragino Sans GB, Microsoft YaHei, sans-serif',
      fontFamilyMono:
        'JetBrains Mono, SF Mono, Fira Code, Consolas, Monaco, Andale Mono, Ubuntu Mono, monospace',
      fontSize: '14px',
      fontSizeMini: '12px',
      fontSizeTiny: '12px',
      fontSizeSmall: '13px',
      fontSizeMedium: '14px',
      fontSizeLarge: '15px',
      fontSizeHuge: '16px',
      lineHeight: '1.5',
      heightMini: '24px',
      heightTiny: '28px',
      heightSmall: '32px',
      heightMedium: '36px',
      heightLarge: '40px',
      heightHuge: '44px',
    },
    Button: {
      borderRadiusMedium: '8px',
      borderRadiusSmall: '6px',
      borderRadiusLarge: '10px',
    },
    Card: {
      borderRadius: '12px',
      paddingMedium: '16px',
      paddingLarge: '20px',
    },
    Input: {
      borderRadius: '8px',
    },
    Select: {
      borderRadius: '8px',
    },
    DataTable: {
      borderRadius: '12px',
    },
    Dialog: {
      borderRadius: '16px',
    },
    Drawer: {
      borderRadius: '0',
    },
    Dropdown: {
      borderRadius: '8px',
    },
    Menu: {
      borderRadius: '8px',
    },
    Message: {
      borderRadius: '8px',
    },
    Notification: {
      borderRadius: '12px',
    },
    Popover: {
      borderRadius: '8px',
    },
    Tag: {
      borderRadius: '6px',
    },
    Tooltip: {
      borderRadius: '6px',
    },
  },
  obsidian: {
    common: {
      primaryColor: '#7c8aff',
      primaryColorHover: '#9da8ff',
      primaryColorPressed: '#5865f2',
      primaryColorSuppl: '#7c8aff',
      infoColor: '#58a6ff',
      infoColorHover: '#79c0ff',
      infoColorPressed: '#388bfd',
      infoColorSuppl: '#58a6ff',
      successColor: '#3fb950',
      successColorHover: '#56d364',
      successColorPressed: '#2ea043',
      successColorSuppl: '#3fb950',
      warningColor: '#d29922',
      warningColorHover: '#e3b341',
      warningColorPressed: '#bb8009',
      warningColorSuppl: '#d29922',
      errorColor: '#f85149',
      errorColorHover: '#ff7b72',
      errorColorPressed: '#da3633',
      errorColorSuppl: '#f85149',
      textColorBase: '#e6edf3',
      textColor1: '#e6edf3',
      textColor2: '#8b949e',
      textColor3: '#6e7681',
      textColorDisabled: '#484f58',
      placeholderColor: '#6e7681',
      placeholderColorDisabled: '#484f58',
      iconColor: '#8b949e',
      iconColorHover: '#e6edf3',
      iconColorPressed: '#e6edf3',
      iconColorDisabled: '#484f58',
      dividerColor: '#30363d',
      borderColor: '#30363d',
      closeIconColor: '#6e7681',
      closeIconColorHover: '#8b949e',
      closeIconColorPressed: '#e6edf3',
      closeColorHover: 'rgba(255, 255, 255, 0.08)',
      closeColorPressed: 'rgba(255, 255, 255, 0.12)',
      clearColor: '#6e7681',
      clearColorHover: '#8b949e',
      clearColorPressed: '#e6edf3',
      scrollbarColor: 'rgba(255, 255, 255, 0.2)',
      scrollbarColorHover: 'rgba(255, 255, 255, 0.3)',
      progressRailColor: '#30363d',
      railColor: '#30363d',
      popoverColor: '#1c2128',
      tableColor: '#1c2128',
      cardColor: '#1c2128',
      modalColor: '#1c2128',
      bodyColor: '#0d1117',
      tagColor: '#262c36',
      avatarColor: '#30363d',
      invertedColor: '#e6edf3',
      inputColor: '#1c2128',
      codeColor: '#262c36',
      tabColor: '#1c2128',
      actionColor: '#262c36',
      tableHeaderColor: '#161b22',
      hoverColor: 'rgba(255, 255, 255, 0.06)',
      tableColorHover: 'rgba(255, 255, 255, 0.06)',
      tableColorStriped: 'rgba(255, 255, 255, 0.03)',
      pressedColor: 'rgba(255, 255, 255, 0.1)',
      opacityDisabled: '0.4',
      inputColorDisabled: '#262c36',
      buttonColor2: 'rgba(124, 138, 255, 0.15)',
      buttonColor2Hover: 'rgba(124, 138, 255, 0.2)',
      buttonColor2Pressed: 'rgba(124, 138, 255, 0.25)',
      boxShadow1: '0 1px 3px 0 rgba(0, 0, 0, 0.4), 0 1px 2px -1px rgba(0, 0, 0, 0.4)',
      boxShadow2: '0 4px 6px -1px rgba(0, 0, 0, 0.45), 0 2px 4px -2px rgba(0, 0, 0, 0.45)',
      boxShadow3: '0 10px 15px -3px rgba(0, 0, 0, 0.5), 0 4px 6px -4px rgba(0, 0, 0, 0.5)',
      borderRadius: '8px',
      borderRadiusSmall: '6px',
      fontFamily:
        'Inter, SF Pro Display, -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Helvetica Neue, Arial, Noto Sans, PingFang SC, Hiragino Sans GB, Microsoft YaHei, sans-serif',
      fontFamilyMono:
        'JetBrains Mono, SF Mono, Fira Code, Consolas, Monaco, Andale Mono, Ubuntu Mono, monospace',
      fontSize: '14px',
      fontSizeMini: '12px',
      fontSizeTiny: '12px',
      fontSizeSmall: '13px',
      fontSizeMedium: '14px',
      fontSizeLarge: '15px',
      fontSizeHuge: '16px',
      lineHeight: '1.5',
      heightMini: '24px',
      heightTiny: '28px',
      heightSmall: '32px',
      heightMedium: '36px',
      heightLarge: '40px',
      heightHuge: '44px',
    },
    Button: {
      borderRadiusMedium: '8px',
      borderRadiusSmall: '6px',
      borderRadiusLarge: '10px',
    },
    Card: {
      borderRadius: '12px',
      paddingMedium: '16px',
      paddingLarge: '20px',
    },
    Input: {
      borderRadius: '8px',
    },
    Select: {
      borderRadius: '8px',
    },
    DataTable: {
      borderRadius: '12px',
    },
    Dialog: {
      borderRadius: '16px',
    },
    Drawer: {
      borderRadius: '0',
    },
    Dropdown: {
      borderRadius: '8px',
    },
    Menu: {
      borderRadius: '8px',
    },
    Message: {
      borderRadius: '8px',
    },
    Notification: {
      borderRadius: '12px',
    },
    Popover: {
      borderRadius: '8px',
    },
    Tag: {
      borderRadius: '6px',
    },
    Tooltip: {
      borderRadius: '6px',
    },
  },
  cyberpunk: {
    common: {
      primaryColor: '#06b6d4',
      primaryColorHover: '#22d3ee',
      primaryColorPressed: '#0891b2',
      primaryColorSuppl: '#06b6d4',
      infoColor: '#8b5cf6',
      infoColorHover: '#a78bfa',
      infoColorPressed: '#7c3aed',
      infoColorSuppl: '#8b5cf6',
      successColor: '#10b981',
      successColorHover: '#34d399',
      successColorPressed: '#059669',
      successColorSuppl: '#10b981',
      warningColor: '#f59e0b',
      warningColorHover: '#fbbf24',
      warningColorPressed: '#d97706',
      warningColorSuppl: '#f59e0b',
      errorColor: '#ef4444',
      errorColorHover: '#f87171',
      errorColorPressed: '#dc2626',
      errorColorSuppl: '#ef4444',
      textColorBase: '#e2e8f0',
      textColor1: '#e2e8f0',
      textColor2: '#94a3b8',
      textColor3: '#64748b',
      textColorDisabled: '#475569',
      placeholderColor: '#64748b',
      placeholderColorDisabled: '#475569',
      iconColor: '#94a3b8',
      iconColorHover: '#e2e8f0',
      iconColorPressed: '#e2e8f0',
      iconColorDisabled: '#475569',
      dividerColor: '#2d3748',
      borderColor: '#2d3748',
      closeIconColor: '#64748b',
      closeIconColorHover: '#94a3b8',
      closeIconColorPressed: '#e2e8f0',
      closeColorHover: 'rgba(255, 255, 255, 0.08)',
      closeColorPressed: 'rgba(255, 255, 255, 0.12)',
      clearColor: '#64748b',
      clearColorHover: '#94a3b8',
      clearColorPressed: '#e2e8f0',
      scrollbarColor: 'rgba(6, 182, 212, 0.3)',
      scrollbarColorHover: 'rgba(6, 182, 212, 0.5)',
      progressRailColor: '#2d3748',
      railColor: '#2d3748',
      popoverColor: '#151b26',
      tableColor: '#151b26',
      cardColor: '#151b26',
      modalColor: '#151b26',
      bodyColor: '#0a0e1a',
      tagColor: '#1a2332',
      avatarColor: '#2d3748',
      invertedColor: '#e2e8f0',
      inputColor: '#151b26',
      codeColor: '#1a2332',
      tabColor: '#151b26',
      actionColor: '#1a2332',
      tableHeaderColor: '#0f1419',
      hoverColor: 'rgba(6, 182, 212, 0.08)',
      tableColorHover: 'rgba(6, 182, 212, 0.08)',
      tableColorStriped: 'rgba(6, 182, 212, 0.04)',
      pressedColor: 'rgba(6, 182, 212, 0.12)',
      opacityDisabled: '0.4',
      inputColorDisabled: '#1a2332',
      buttonColor2: 'rgba(6, 182, 212, 0.15)',
      buttonColor2Hover: 'rgba(6, 182, 212, 0.2)',
      buttonColor2Pressed: 'rgba(6, 182, 212, 0.25)',
      boxShadow1: '0 1px 3px 0 rgba(6, 182, 212, 0.1), 0 1px 2px -1px rgba(0, 0, 0, 0.4)',
      boxShadow2: '0 4px 6px -1px rgba(6, 182, 212, 0.15), 0 2px 4px -2px rgba(0, 0, 0, 0.45)',
      boxShadow3: '0 10px 15px -3px rgba(6, 182, 212, 0.2), 0 4px 6px -4px rgba(0, 0, 0, 0.5)',
      borderRadius: '8px',
      borderRadiusSmall: '6px',
      fontFamily:
        'Inter, SF Pro Display, -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Helvetica Neue, Arial, Noto Sans, PingFang SC, Hiragino Sans GB, Microsoft YaHei, sans-serif',
      fontFamilyMono:
        'JetBrains Mono, SF Mono, Fira Code, Consolas, Monaco, Andale Mono, Ubuntu Mono, monospace',
      fontSize: '14px',
      fontSizeMini: '12px',
      fontSizeTiny: '12px',
      fontSizeSmall: '13px',
      fontSizeMedium: '14px',
      fontSizeLarge: '15px',
      fontSizeHuge: '16px',
      lineHeight: '1.5',
      heightMini: '24px',
      heightTiny: '28px',
      heightSmall: '32px',
      heightMedium: '36px',
      heightLarge: '40px',
      heightHuge: '44px',
    },
    Button: {
      borderRadiusMedium: '8px',
      borderRadiusSmall: '6px',
      borderRadiusLarge: '10px',
      textColorPrimary: '#0a0e1a',
      textColorHoverPrimary: '#0a0e1a',
      textColorPressedPrimary: '#0a0e1a',
      textColorFocusPrimary: '#0a0e1a',
    },
    Card: {
      borderRadius: '12px',
      paddingMedium: '16px',
      paddingLarge: '20px',
    },
    Input: {
      borderRadius: '8px',
    },
    Select: {
      borderRadius: '8px',
    },
    DataTable: {
      borderRadius: '12px',
    },
    Dialog: {
      borderRadius: '16px',
    },
    Drawer: {
      borderRadius: '0',
    },
    Dropdown: {
      borderRadius: '8px',
    },
    Menu: {
      borderRadius: '8px',
    },
    Message: {
      borderRadius: '8px',
    },
    Notification: {
      borderRadius: '12px',
    },
    Popover: {
      borderRadius: '8px',
    },
    Tag: {
      borderRadius: '6px',
    },
    Tooltip: {
      borderRadius: '6px',
    },
  },
  sakura: {
    common: {
      primaryColor: '#ff6b9d',
      primaryColorHover: '#ff8fb5',
      primaryColorPressed: '#ff4d8a',
      primaryColorSuppl: '#ff6b9d',
      infoColor: '#74c0fc',
      infoColorHover: '#91d7ff',
      infoColorPressed: '#4dabf7',
      infoColorSuppl: '#74c0fc',
      successColor: '#69db7c',
      successColorHover: '#8ce99a',
      successColorPressed: '#51cf66',
      successColorSuppl: '#69db7c',
      warningColor: '#ffd43b',
      warningColorHover: '#ffe066',
      warningColorPressed: '#fcc419',
      warningColorSuppl: '#ffd43b',
      errorColor: '#ff8787',
      errorColorHover: '#ffa8a8',
      errorColorPressed: '#ff6b6b',
      errorColorSuppl: '#ff8787',
      textColorBase: '#2d2d2d',
      textColor1: '#2d2d2d',
      textColor2: '#5c5c5c',
      textColor3: '#9e9e9e',
      textColorDisabled: '#d4d4d4',
      placeholderColor: '#9e9e9e',
      placeholderColorDisabled: '#d4d4d4',
      iconColor: '#5c5c5c',
      iconColorHover: '#2d2d2d',
      iconColorPressed: '#2d2d2d',
      iconColorDisabled: '#d4d4d4',
      dividerColor: '#ffc2d1',
      borderColor: '#ffc2d1',
      closeIconColor: '#9e9e9e',
      closeIconColorHover: '#5c5c5c',
      closeIconColorPressed: '#2d2d2d',
      closeColorHover: 'rgba(255, 107, 157, 0.08)',
      closeColorPressed: 'rgba(255, 107, 157, 0.12)',
      clearColor: '#9e9e9e',
      clearColorHover: '#5c5c5c',
      clearColorPressed: '#2d2d2d',
      scrollbarColor: 'rgba(255, 107, 157, 0.3)',
      scrollbarColorHover: 'rgba(255, 107, 157, 0.4)',
      progressRailColor: '#ffe4e9',
      railColor: '#ffe4e9',
      popoverColor: '#ffffff',
      tableColor: '#ffffff',
      cardColor: '#ffffff',
      modalColor: '#ffffff',
      bodyColor: '#fff5f7',
      tagColor: '#ffe4e9',
      avatarColor: '#ffc2d1',
      invertedColor: '#2d2d2d',
      inputColor: '#ffffff',
      codeColor: '#ffe4e9',
      tabColor: '#ffffff',
      actionColor: '#ffe4e9',
      tableHeaderColor: '#fff5f7',
      hoverColor: 'rgba(255, 107, 157, 0.06)',
      tableColorHover: 'rgba(255, 107, 157, 0.06)',
      tableColorStriped: 'rgba(255, 107, 157, 0.03)',
      pressedColor: 'rgba(255, 107, 157, 0.1)',
      opacityDisabled: '0.5',
      inputColorDisabled: '#ffe4e9',
      buttonColor2: 'rgba(255, 107, 157, 0.1)',
      buttonColor2Hover: 'rgba(255, 107, 157, 0.15)',
      buttonColor2Pressed: 'rgba(255, 107, 157, 0.2)',
      boxShadow1: '0 1px 3px 0 rgba(255, 107, 157, 0.1), 0 1px 2px -1px rgba(0, 0, 0, 0.06)',
      boxShadow2: '0 4px 6px -1px rgba(255, 107, 157, 0.12), 0 2px 4px -2px rgba(0, 0, 0, 0.07)',
      boxShadow3: '0 10px 15px -3px rgba(255, 107, 157, 0.15), 0 4px 6px -4px rgba(0, 0, 0, 0.08)',
      borderRadius: '8px',
      borderRadiusSmall: '6px',
      fontFamily:
        'Inter, SF Pro Display, -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Helvetica Neue, Arial, Noto Sans, PingFang SC, Hiragino Sans GB, Microsoft YaHei, sans-serif',
      fontFamilyMono:
        'JetBrains Mono, SF Mono, Fira Code, Consolas, Monaco, Andale Mono, Ubuntu Mono, monospace',
      fontSize: '14px',
      fontSizeMini: '12px',
      fontSizeTiny: '12px',
      fontSizeSmall: '13px',
      fontSizeMedium: '14px',
      fontSizeLarge: '15px',
      fontSizeHuge: '16px',
      lineHeight: '1.5',
      heightMini: '24px',
      heightTiny: '28px',
      heightSmall: '32px',
      heightMedium: '36px',
      heightLarge: '40px',
      heightHuge: '44px',
    },
    Button: {
      borderRadiusMedium: '8px',
      borderRadiusSmall: '6px',
      borderRadiusLarge: '10px',
    },
    Card: {
      borderRadius: '12px',
      paddingMedium: '16px',
      paddingLarge: '20px',
    },
    Input: {
      borderRadius: '8px',
    },
    Select: {
      borderRadius: '8px',
    },
    DataTable: {
      borderRadius: '12px',
    },
    Dialog: {
      borderRadius: '16px',
    },
    Drawer: {
      borderRadius: '0',
    },
    Dropdown: {
      borderRadius: '8px',
    },
    Menu: {
      borderRadius: '8px',
    },
    Message: {
      borderRadius: '8px',
    },
    Notification: {
      borderRadius: '12px',
    },
    Popover: {
      borderRadius: '8px',
    },
    Tag: {
      borderRadius: '6px',
    },
    Tooltip: {
      borderRadius: '6px',
    },
  },
}

/**
 * Naive UI 主题 composable
 * 与 useTheme 配合使用，提供 Naive UI 的主题配置
 */
export function useNaiveTheme() {
  const { currentTheme, isDark } = useTheme()

  /**
   * 当前 Naive UI 主题（深色/浅色）
   */
  const naiveTheme = computed(() => {
    return isDark.value ? darkTheme : null
  })

  /**
   * 当前 Naive UI 主题覆盖配置
   */
  const naiveThemeOverrides = computed(() => {
    return themeOverridesMap[currentTheme.value]
  })

  return {
    naiveTheme,
    naiveThemeOverrides,
  }
}

export { getCssVar }
